### ISSUE TITLE
Structuring CSS code

### ISSUE THREAD

**Issue by ghost** [joostflick/web-app-from-scratch-18-19#1]
https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/public/css/styles.css#L1

Try to structure CSS file to prevent trouble in the future. 

[Link](https://css-tricks.com/methods-organize-css/)

**Comment by joostflick** [comment]
I will take a look
