### ISSUE TITLE
Speech

### ISSUE THREAD

**Issue by RobinStut** [joostflick/web-app-from-scratch-18-19#2]
https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/index.html#L13

Wat leuk dat je text to speech gebruikt. Misschien is het slim om een pauze knop in te stellen als je de spraak wilt gaan pauzeren

**Comment by maanlamp** [comment]
Don' t use inline Javascript though :)
Use `addEventListener` in your js.

**Comment by joostflick** [comment]
moved inline js to my js file, decided not to add a pause button @RobinStut
