### ISSUE TITLE
Unused function?

### ISSUE THREAD

**Issue by maanlamp** [joostflick/web-app-from-scratch-18-19#3]
https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/public/js/app.js#L35-L41

Any reason this function exists when you' re not using it anywhere?

**Comment by joostflick** [comment]
@maanlamp I'm currently using this function in my html [link](https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/index.html#L15). It might be better to use an eventlistener for this though

**Comment by joostflick** [comment]
function call moved to js file
