### ISSUE TITLE
Use template literal?

### ISSUE THREAD

**Issue by maanlamp** [joostflick/web-app-from-scratch-18-19#4]
https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/public/js/app.js#L21

If you want, you can rewrite this to:
``` js
`"${quotes.messages.non_personalized[randNum]}"`
```

Saves some typing and IMO looks better. If you don' t want to, just close this :)

**Comment by joostflick** [comment]
I agree this looks better, just changed it, thanks
