### ISSUE TITLE
var / let / const

### ISSUE THREAD

**Issue by TuriGuilano** [joostflick/web-app-from-scratch-18-19#7]
I see you are using var and let, no const.. why?

https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/public/js/app.js#L7

https://github.com/joostflick/web-app-from-scratch-18-19/blob/32ed06f4be9c3c517697be3d31b95dd918833fd4/week1/public/js/list.js#L1-L2

Try to understand in dept the difference between the three before implementing.

**Comment by joostflick** [comment]
Code has been updated, exclusively using const and let now so consistency +1
